src/main/python/ttconv/imsc/style_properties.py
src/main/python/ttconv/model.py
src/main/python/ttconv/style_properties.py
src/test/python/test_imsc_color_parser.py
src/test/python/test_model_style_properties.py

... and add basic style property unit test
Closes #30

Add support for stereoscopic 3D

---

src/main/python/ttconv/model.py
src/test/python/test_model_element.py

Add support for discrete animation to the model

---

src/main/python/ttconv/model.py
src/test/python/test_model_document.py

Add display aspect ratio control to Document

---

src/main/python/ttconv/imsc/imsc_reader.py
src/main/python/ttconv/model.py
src/test/python/test_model_document.py

Add support for active area signaling

---

README.md
doc/data_model.md

Document the data model

---

src/main/python/ttconv/scc/codes/special_characters.py
src/main/python/ttconv/scc/scc_reader.py
src/test/python/test_scc_reader.py
src/test/python/test_scc_special_characters.py

SCC special characters support

---

.coveragerc
Pipfile
Pipfile.lock
scripts/coverage.sh
src/main/python/ttconv/imsc/elements.py

Added coverage scripts and pre-requisites
Closes #61 
Closes #34

Set elements now processed

---

.gitmodules
src/main/python/ttconv/imsc/elements.py
src/main/python/ttconv/imsc/style_properties.py
src/main/python/ttconv/imsc/utils.py
src/main/python/ttconv/style_properties.py
src/test/python/test_imsc_position_parser.py

Implement support for tts:position in IMSC reader (#36)

---

src/main/python/ttconv/model.py
src/test/python/test_model_document.py

Remove default active area from document model

---

README.md
doc/imsc_reader.md
doc/references.md
src/main/python/ttconv/imsc/attributes.py
src/main/python/ttconv/imsc/elements.py
src/main/python/ttconv/imsc/style_properties.py
src/test/python/test_imsc_writer.py

Closes #39
Closes #37 
Closes #57

Misc documentation and linting fixes

---

src/main/python/ttconv/imsc/elements.py
src/main/python/ttconv/imsc/style_properties.py
src/test/python/test_imsc_writer.py

Serialize tts:origin and refactor naming of IMSC styles processing methods

---

src/main/python/ttconv/imsc/elements.py

Fix Region output of IMSC writer

---

src/main/python/ttconv/imsc/style_properties.py

Fix tts:extent serialization

---

src/main/python/ttconv/scc/paragraph.py
src/main/python/ttconv/scc/reader.py
src/main/python/ttconv/scc/utils.py
src/test/python/test_scc_reader.py
src/test/python/test_scc_region.py

 SCC reader output length in percentage units

---

src/main/python/ttconv/scc/paragraph.py
src/main/python/ttconv/scc/reader.py
src/test/python/test_scc_paragraph.py
src/test/python/test_scc_reader.py

SCC: default paragraphs black background color

---

src/main/python/ttconv/scc/paragraph.py
src/test/python/test_scc_reader.py

SCC: paint-on nested times fix

---

src/main/python/ttconv/scc/disassembly.py
src/main/python/ttconv/scc/reader.py
src/test/python/test_scc_disassembly.py

SCC disassembly format

---

README.md

Update README with a quick start

---

src/main/python/ttconv/scc/paragraph.py
src/test/python/test_scc_reader.py

Based on PR https://github.com/sandflow/ttconv/pull/100
Closes #96

SCC reader to taller regions for pop-on and paint-on captions

---

src/main/python/ttconv/scc/paragraph.py
src/test/python/test_scc_reader.py

SCC: display align after on roll-up regions

---

doc/isd.md
src/main/python/ttconv/imsc/attributes.py
src/main/python/ttconv/imsc/elements.py
src/main/python/ttconv/imsc/style_properties.py
src/main/python/ttconv/imsc/utils.py
src/main/python/ttconv/isd.py
src/main/python/ttconv/model.py
src/main/python/ttconv/scc/codes/preambles_address_codes.py
src/main/python/ttconv/scc/content.py
src/main/python/ttconv/scc/paragraph.py
src/main/python/ttconv/scc/reader.py
src/main/python/ttconv/scc/time_codes.py
src/main/python/ttconv/style_properties.py
src/test/python/test_imsc_reader.py
src/test/python/test_imsc_writer.py
src/test/python/test_isd.py
src/test/python/test_model_document.py

Closes #110 
Closes #111
Closes #114

Initial ISD implementation

---

src/main/python/ttconv/tt.py
src/test/python/test_tt.py

Implementing args for indicating file type (#93)

---

src/main/python/ttconv/scc/disassembly.py
src/test/python/test_scc_disassembly.py

SCC: fixes disassembly format text decoration support

---

src/test/python/test_imsc_writer.py

Fixing use of strings for LengthType constructor (#135)

---

src/main/python/ttconv/isd.py
src/test/python/test_isd.py

Add support for default region during ISD construction

---

src/main/python/ttconv/isd.py
src/test/python/test_isd.py

Handle display=None during ISD processing

---

src/main/python/ttconv/imsc/elements.py
src/main/python/ttconv/isd.py
src/test/python/test_isd_lwsp.py
src/test/resources/ttml/lwsp_default.ttml
src/test/resources/ttml/lwsp_preserve.ttml

Strip whitespace during ISD construction

---

src/main/python/ttconv/scc/reader.py
src/test/python/test_scc_reader.py

SCC reader handles ENM control code

---

src/test/python/test_srt_writer.py

Remove IMSC 1.2 test suite from SRT writer unit tests

---

doc/data_model.md
doc/imsc_reader.md
doc/isd.md
src/main/python/ttconv/imsc/elements.py
src/main/python/ttconv/imsc/reader.py
src/main/python/ttconv/imsc/style_properties.py
src/main/python/ttconv/imsc/writer.py
src/main/python/ttconv/isd.py
src/main/python/ttconv/model.py
src/main/python/ttconv/scc/paragraph.py
src/main/python/ttconv/scc/reader.py
src/main/python/ttconv/srt/writer.py
src/test/python/test_filter_default_style_properties.py
src/test/python/test_filter_supported_style_properties.py
src/test/python/test_imsc_writer.py
src/test/python/test_isd.py
src/test/python/test_model_document.py
src/test/python/test_model_element.py
src/test/python/test_scc_paragraph.py
src/test/python/test_scc_region.py
src/test/python/test_srt_writer.py

Changed Document class to ContentDocument

---

src/main/python/ttconv/imsc/elements.py
src/main/python/ttconv/imsc/style_properties.py
src/test/python/test_imsc_writer.py

Fix IMSC Writer ruby output

---

src/main/python/ttconv/tt.py

SRT output is UTF-8 encoded

---

src/main/python/ttconv/imsc/style_properties.py
src/main/python/ttconv/style_properties.py

Make Fontfamily style property immutable

---

src/main/python/ttconv/imsc/attributes.py
src/main/python/ttconv/imsc/elements.py
src/main/python/ttconv/imsc/writer.py

Clean-up method signatures and inheritance in imsc/element.py

---

src/main/python/ttconv/imsc/elements.py
src/test/python/test_imsc_reader.py

Report out-of-order set elements

---

src/test/python/test_isd.py
src/test/python/test_model_document.py
src/test/python/test_model_element.py

Changing date model to data model typo (#120)

---

src/test/python/test_filter_default_style_properties.py
src/test/python/test_filter_merge_paragraphs.py
src/test/python/test_filter_merge_regions.py
src/test/python/test_filter_supported_style_properties.py
src/test/python/test_scc_attribute_codes.py
src/test/python/test_scc_content.py
src/test/python/test_scc_control_codes.py
src/test/python/test_scc_disassembly.py
src/test/python/test_scc_mid_row_codes.py
src/test/python/test_scc_paragraph.py
src/test/python/test_scc_region.py
src/test/python/test_scc_special_characters.py
src/test/python/test_srt_paragraph.py
src/test/python/test_srt_style.py
src/test/python/test_srt_writer.py
src/test/python/test_time_code.py
src/test/python/test_time_code_smpte.py

Adding __main__ to all unit tests (#193)

---

src/main/python/ttconv/imsc/attributes.py
src/main/python/ttconv/imsc/elements.py
src/main/python/ttconv/imsc/style_properties.py
src/main/python/ttconv/time_code.py
src/test/python/test_imsc_writer.py
src/test/python/test_time_code.py

Closes #175
Closes #176
Closes #177
Closes #178
Closes #179
Closes #180
Closes #181
Closes #182
Closes #183
Closes #184
Closes #185
Closes #186
Closes #187
Closes #188

Addresses multiple IMSC reading/writing issues

---

src/main/python/ttconv/imsc/attributes.py
src/main/python/ttconv/imsc/elements.py
src/main/python/ttconv/imsc/reader.py
src/main/python/ttconv/imsc/style_properties.py
src/main/python/ttconv/imsc/utils.py
src/main/python/ttconv/isd.py
src/main/python/ttconv/model.py
src/main/python/ttconv/scc/codes/attribute_codes.py

Verify typing hints

---

doc/references.md

Add reference to FCC regulations

---

src/main/python/ttconv/imsc/attributes.py
src/main/python/ttconv/imsc/elements.py
src/main/python/ttconv/imsc/namespaces.py

Refactored xml namespace definition and region attribute serialization

---

src/main/python/ttconv/imsc/style_properties.py
src/main/python/ttconv/imsc/utils.py
src/main/python/ttconv/style_properties.py
src/test/python/test_imsc_font_families_parser.py

Fix FontFamily writing and reading

---

doc/data_model.md
doc/isd.md
scripts/linter.sh
scripts/unit_test.sh
setup.py
src/main/python/ttconv/imsc/style_properties.py
src/main/python/ttconv/isd.py
src/main/python/ttconv/model.py
src/main/python/ttconv/scc/content.py
src/main/python/ttconv/scc/paragraph.py
src/main/python/ttconv/scc/utils.py
src/main/python/ttconv/style_properties.py
src/test/python/test_imsc_writer.py
src/test/python/test_isd.py
src/test/python/test_scc_content.py
src/test/python/test_scc_reader.py
src/test/python/test_tt.py

Fix edge relative positioning

---

README.md
doc/scc_reader.md
doc/srt_writer.md
setup.py
src/main/python/ttconv/tt.py
src/test/python/test_srt_writer.py
src/test/python/test_tt.py

Remove not-implemented `validate` subcommand
Update README

1.0.0 Release Candidate 2

---

src/main/python/ttconv/scc/reader.py

Set LineHeight to 100% in SCC Reader

---

.github/workflows/main.yml
src/main/python/ttconv/imsc/attributes.py

Fix ttp:cellResolution serialization in IMSC Writer

---

src/main/python/ttconv/scc/codes/special_characters.py
src/test/python/test_scc_special_characters.py

Improve CEA 608 character mappings

---

src/main/python/ttconv/imsc/writer.py

Use "ebutts" as the prefix for the EBU TT Style ns

---

src/main/python/ttconv/scc/paragraph.py
src/test/python/test_scc_reader.py
src/test/python/test_scc_region.py

SCC: ShowBackground should be set to "whenActive" on region elements

---

src/main/python/ttconv/scc/line.py
src/main/python/ttconv/scc/reader.py
src/main/python/ttconv/scc/word.py
src/test/python/test_scc_line.py
src/test/python/test_scc_reader.py
src/test/python/test_scc_word.py

Bound to https://github.com/sandflow/ttconv/issues/217#issuecomment-780582472

SCC line break missing

---

src/main/python/ttconv/scc/codes/control_codes.py
src/test/python/test_scc_control_codes.py

SCC reader handles Field 2 control codes

---

src/main/python/ttconv/scc/reader.py

SCC: fix field 2 control codes support

---

src/main/python/ttconv/scc/paragraph.py

SCC: fixes matching region assignment

---

src/main/python/ttconv/scc/paragraph.py
src/main/python/ttconv/scc/reader.py
src/test/python/test_scc_reader.py

Set background on span for SCC reader output
Closes #221 
Closes #222

Improve font family in SCC reader output

---

README.md
src/main/python/ttconv/tt.py
src/test/python/test_tt.py

Accept lower and uppercase file types in tt.py (#239)

---

src/main/python/ttconv/scc/reader.py

SCC reader sets ActiveArea to the safe area

---

src/main/python/ttconv/scc/content.py
src/main/python/ttconv/scc/paragraph.py
src/main/python/ttconv/scc/reader.py
src/test/python/test_scc_content.py
src/test/python/test_scc_paragraph.py
src/test/python/test_scc_reader.py
src/test/python/test_scc_region.py

SCC reader avoids overlapping regions

---

src/main/python/ttconv/isd.py
src/main/python/ttconv/model.py
src/test/python/test_model_document.py
src/test/python/test_model_element.py

Improve ISD generation performance

---

src/main/python/ttconv/scc/paragraph.py
src/main/python/ttconv/scc/reader.py

SCC text styling improvement

---

src/main/python/ttconv/scc/content.py
src/main/python/ttconv/scc/paragraph.py
src/main/python/ttconv/scc/reader.py
src/test/python/test_scc_reader.py

SCC reader always creates a caption on EDM

---

src/main/python/ttconv/scc/reader.py
src/test/python/test_scc_reader.py

SCC: fix exclusive end time attribute

---

src/main/python/ttconv/tt.py

Change IMSC output encoding to UTF-8

---

src/main/python/ttconv/stl/datafile.py

Fix STL vertical alignment (closes #272)
Fix STL line height (closes #271)

Misc STL fixes

---

src/main/python/ttconv/stl/datafile.py
src/main/python/ttconv/stl/tf.py

Fix multiple block support

---

README.md
src/main/python/ttconv/stl/config.py
src/main/python/ttconv/stl/datafile.py
src/main/python/ttconv/stl/reader.py
src/test/python/test_stl_reader_config.py

Add tts:fillLineGap option to STL reader

---

README.md
src/main/python/ttconv/stl/config.py
src/main/python/ttconv/stl/datafile.py
src/main/python/ttconv/stl/reader.py
src/test/python/test_stl_reader_config.py

Add support for line padding in STL reader

---

src/main/python/ttconv/stl/datafile.py
src/test/python/test_stl_reader.py

Fix fontSize for STL cumulative subtitles

---

src/main/python/ttconv/stl/datafile.py

Fix STL region height with double height characters

---

README.md
doc/references.md
src/main/python/ttconv/stl/config.py
src/main/python/ttconv/stl/datafile.py
src/main/python/ttconv/stl/iso6937.py
src/main/python/ttconv/stl/tf.py

Complete EBU STL reader documentation

---

src/main/python/ttconv/tt.py

Protect progress bar against values outside of [0,1]

---

README.md
src/main/python/ttconv/stl/config.py
src/main/python/ttconv/stl/datafile.py
src/test/python/test_stl_reader.py
src/test/python/test_stl_reader_config.py

Ignore TCP GSI field by default

---

src/main/python/ttconv/stl/datafile.py

Add 24 fps and 23.98 fps

---

src/main/python/ttconv/stl/datafile.py
src/main/python/ttconv/stl/tf.py

Treat sequence of two newlines as one

---

src/main/python/ttconv/stl/datafile.py
src/test/python/test_stl_reader.py

Add activeArea signaling to STL reader

---

src/main/python/ttconv/srt/paragraph.py
src/main/python/ttconv/srt/writer.py

Fix handling of empty ISDs in SRT writer

---

README.md
src/main/python/ttconv/imsc/attributes.py
src/main/python/ttconv/imsc/config.py
src/main/python/ttconv/imsc/elements.py
src/main/python/ttconv/imsc/writer.py
src/test/python/test_config.py
src/test/python/test_imsc_writer.py

TTML writer: support time-clock-with-frames output

---

src/main/python/ttconv/imsc/config.py
src/test/python/test_imsc_writer.py

imsc writer: fix config parsing

---

src/main/python/ttconv/tt.py

tt: fix minor typo

---

README.md
src/main/python/ttconv/config.py

tt: set default log_level to "INFO"

---

src/main/python/ttconv/scc/reader.py

SCC: Fix of the duplicated caption at the end of some files

---

README.md
src/main/python/ttconv/config.py
src/main/python/ttconv/tt.py
src/test/python/test_config.py
src/test/python/test_tt.py

tt: add the ability to override the top-level language of the input document

---

README.md
src/main/python/ttconv/vtt/config.py
src/main/python/ttconv/vtt/cue.py
src/main/python/ttconv/vtt/writer.py
src/test/python/test_vtt_cue.py
src/test/python/test_vtt_writer.py

Make numbering of WebVTT cues optional

---

src/main/python/ttconv/imsc/style_properties.py
src/test/python/test_imsc_reader.py

Fix default values for tts:textEmphasis

---

setup.py
src/main/python/ttconv/isd.py
src/test/python/test_isd.py

ISD: fix error on computing tts:textEmphasis="auto"

---

src/main/python/ttconv/style_properties.py

model: Fix initial value of LinePadding style

---

src/main/python/ttconv/isd.py
src/test/python/test_isd.py

Implement tts:direction special inheritance

---

setup.py

Release planned for 2025-01-06
RC deployed at: https://pypi.org/project/ttconv/1.1.1rc1/

1.1.1 release

---

src/main/python/ttconv/vtt/reader.py
src/test/python/test_vtt_reader.py

Fix VTT reader timestamp tag bug

---

src/main/python/ttconv/imsc/attributes.py
src/main/python/ttconv/imsc/utils.py
src/test/python/test_imsc_time_expressions.py

IMSC reader: tolerate some bad time expressions

---

.github/workflows/main.yml
src/main/python/ttconv/scc/context.py
src/main/python/ttconv/scc/line.py
src/test/python/test_scc_reader.py

Fix SCC timestamp alignment
